import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Global/Footer";
import ScrollToTopButton from "@/components/Global/ScrollToTopButton";
import { ThemeProvider } from "@/context/ThemeContext";
import DonateButton from "@/components/Global/DonateButton";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Palmcare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <ScrollToTopButton />
          <DonateButton />

          {/* <Navbar /> */}
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
